#!/bin/csh -f

#   ////////////////////////////////////////////////////////////////////////////////////////////////
#   //                                                                                            //
#   // Copyright (2022) Patrick A. Bonnaud                                                        //
#   //                                                                                            //
#   // This file is part of BUILDLIBRARY (Build Molecular Models for a Library of Molecules).     //
#   //                                                                                            //
#   // BUILDLIBRARY is free software; you can redistribute it and/or modify it under the terms    //
#   // of the GNU General Public License as published by the Free Software Foundation; either     //
#   // version 2 of the License, or (at your option) any later version.                           //
#   //                                                                                            //
#   // BUILDLIBRARY is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;  //
#   // without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  //
#   // See the GNU General Public License for more details.                                       //
#   //                                                                                            //
#   // You should have received a copy of the GNU General Public License along with this program. //
#   // If not, see <http://www.gnu.org/licenses/>.                                                //
#   //                                                                                            //
#   ////////////////////////////////////////////////////////////////////////////////////////////////

rm -f log

echo 'COMPILATION 1'

 /opt/intel/Compiler/11.1/073/bin/ia32/ifort *.f90 -o SLAB100_P4.exe

echo
echo 'COMPILATION 2'
echo

 /opt/intel/Compiler/11.1/073/bin/ia32/ifort *.f90 -o SLAB100_P4.exe

echo
echo 'COMPILATION P4 OK'
echo

echo 'COMPILATION 1'

ifort -O3 *.f90 -o SLAB100_AMD.exe

echo
echo 'COMPILATION 2'
echo

ifort -O3 *.f90 -o SLAB100_AMD.exe

echo 'COMPILATION AMD OK'



